language: node_js
sudo: false

node_js:
  - "6.0"
  - "6.1"
  - "6.2"
  - "6.3"
  - "6.4"

cache:
  directories:
    - node_modules

# services:
#   - elasticsearch

os:
  - linux
#  - osx

script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true"
